### ISSUE TITLE
Extend dashboard query with 'Alias' field

### ISSUE THREAD

**Issue by JSAnyone** [fetzerch/grafana-sunandmoon-datasource#33]
Hi,
This is a really useful Plugin for PV-Monitoring!
Would it be possible to give the user the option to rename Series, like the "Alias by" field does it with InfluxDB?
I know that this isn't a key feature, but it would be very useful, especially if you want to create dashboards that should be understandable for people not speaking English.

**Comment by fetzerch** [comment]
Thanks, valid request which I had on my list as well for a while.

**Comment by fetzerch** [comment]
I did get the hint, that it's possible already by using a [transformation](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#organize-fields) in Grafana.

Since this is the preferred way and the [Grafana team wants to phase out providing aliases for plugins](https://github.com/grafana/grafana-plugin-repository/pull/789#issuecomment-731050580) anyways, I won't add this anymore.
